/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.gti.asd.gui.vending;

import edu.gti.asd.gui.vending.utils.JTextFieldUtils;
import edu.gti.asd.gui.vending.utils.Logger;

/**
 *
 * @author ariel
 */
public class AdminAddProducts extends javax.swing.JFrame {

    /**
     * Creates new form AdminAddProducts
     */
    public AdminAddProducts() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jTextFieldAddCoca = new javax.swing.JTextField();
        jTextField7up = new javax.swing.JTextField();
        jTextFieldFanta = new javax.swing.JTextField();
        jTextFieldSchweps = new javax.swing.JTextField();
        jButtonAddStock = new javax.swing.JButton();
        jTextFieldPriceCoca = new javax.swing.JTextField();
        jTextFieldPrice7up = new javax.swing.JTextField();
        jTextFieldPriceFanta = new javax.swing.JTextField();
        jTextFieldPriceSchweps = new javax.swing.JTextField();
        jButtonAddCoke = new javax.swing.JButton();
        jButtonSubstractCoke = new javax.swing.JButton();
        jButtonAdd7Up = new javax.swing.JButton();
        jButtonAddFanta = new javax.swing.JButton();
        jButtonAddSchweps = new javax.swing.JButton();
        jButtonSubstract7Up = new javax.swing.JButton();
        jButtonSubstractFanta = new javax.swing.JButton();
        jButtonSubstractSchweps = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jToggleButton1.setText("Coca");
        jToggleButton1.setEnabled(false);
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jToggleButton2.setText("7up");
        jToggleButton2.setEnabled(false);
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        jToggleButton3.setText("Fanta");
        jToggleButton3.setEnabled(false);
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });

        jToggleButton4.setText("Schweps");
        jToggleButton4.setEnabled(false);
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });

        jTextFieldAddCoca.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTextFieldAddCoca.setText("0");
        jTextFieldAddCoca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldAddCocaKeyTyped(evt);
            }
        });

        jTextField7up.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTextField7up.setText("0");
        jTextField7up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7upActionPerformed(evt);
            }
        });
        jTextField7up.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField7upKeyTyped(evt);
            }
        });

        jTextFieldFanta.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTextFieldFanta.setText("0");
        jTextFieldFanta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldFantaKeyTyped(evt);
            }
        });

        jTextFieldSchweps.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTextFieldSchweps.setText("0");
        jTextFieldSchweps.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldSchwepsKeyTyped(evt);
            }
        });

        jButtonAddStock.setText("Add Stock and update price");
        jButtonAddStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddStockActionPerformed(evt);
            }
        });

        jTextFieldPriceCoca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldPriceCocaKeyTyped(evt);
            }
        });

        jTextFieldPrice7up.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldPrice7upKeyTyped(evt);
            }
        });

        jTextFieldPriceFanta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldPriceFantaKeyTyped(evt);
            }
        });

        jTextFieldPriceSchweps.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldPriceSchwepsKeyTyped(evt);
            }
        });

        jButtonAddCoke.setText("+");
        jButtonAddCoke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddCokeActionPerformed(evt);
            }
        });

        jButtonSubstractCoke.setText("-");
        jButtonSubstractCoke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubstractCokeActionPerformed(evt);
            }
        });

        jButtonAdd7Up.setText("+");
        jButtonAdd7Up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdd7UpActionPerformed(evt);
            }
        });

        jButtonAddFanta.setText("+");
        jButtonAddFanta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddFantaActionPerformed(evt);
            }
        });

        jButtonAddSchweps.setText("+");
        jButtonAddSchweps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddSchwepsActionPerformed(evt);
            }
        });

        jButtonSubstract7Up.setText("-");
        jButtonSubstract7Up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubstract7UpActionPerformed(evt);
            }
        });

        jButtonSubstractFanta.setText("-");
        jButtonSubstractFanta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubstractFantaActionPerformed(evt);
            }
        });

        jButtonSubstractSchweps.setText("-");
        jButtonSubstractSchweps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubstractSchwepsActionPerformed(evt);
            }
        });

        jLabel1.setText("Quantity");

        jLabel2.setText("Price");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonAddStock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jToggleButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleButton4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonAddCoke)
                            .addComponent(jButtonAdd7Up)
                            .addComponent(jButtonAddFanta)
                            .addComponent(jButtonAddSchweps))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldAddCoca, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField7up, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldFanta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldSchweps, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonSubstractCoke)
                            .addComponent(jButtonSubstract7Up)
                            .addComponent(jButtonSubstractFanta)
                            .addComponent(jButtonSubstractSchweps))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldPriceFanta, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldPriceCoca, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldPriceSchweps, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldPrice7up, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(41, 41, 41))
            .addGroup(layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(63, 63, 63))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldAddCoca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPriceCoca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAddCoke)
                    .addComponent(jButtonSubstractCoke))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField7up, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPrice7up, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAdd7Up)
                    .addComponent(jButtonSubstract7Up))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldFanta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPriceFanta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAddFanta)
                    .addComponent(jButtonSubstractFanta))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSchweps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPriceSchweps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAddSchweps)
                    .addComponent(jButtonSubstractSchweps))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonAddStock, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton4ActionPerformed

    private void jButtonAddStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddStockActionPerformed
        Logger.info("AdminAddProducts.jButtonAddStockActionPerformed", "Adding products into machine stock...");
        int quantityCoca = Integer.parseInt(jTextFieldAddCoca.getText());
        int quantity7up = Integer.parseInt(jTextField7up.getText());
        int quantityFanta = Integer.parseInt(jTextFieldFanta.getText());
        int quantitySchweps = Integer.parseInt(jTextFieldSchweps.getText());
        
        VendingMachine.productCoca.incrementStock(quantityCoca);
        VendingMachine.product7up.incrementStock(quantity7up);
        VendingMachine.productFanta.incrementStock(quantityFanta);
        VendingMachine.productSchweps.incrementStock(quantitySchweps);
        
        VendingMachine.productCoca.setPrice(Double.parseDouble(jTextFieldPriceCoca.getText()));
        VendingMachine.product7up.setPrice(Double.parseDouble(jTextFieldPrice7up.getText()));
        VendingMachine.productFanta.setPrice(Double.parseDouble(jTextFieldPriceFanta.getText()));
        VendingMachine.productSchweps.setPrice(Double.parseDouble(jTextFieldPriceSchweps.getText()));
        
        dispose();
        
    }//GEN-LAST:event_jButtonAddStockActionPerformed

    private void jTextFieldAddCocaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldAddCocaKeyTyped
        JTextFieldUtils.onlyDigitsOnKeyTyped(evt);
    }//GEN-LAST:event_jTextFieldAddCocaKeyTyped

    private void jTextFieldPriceCocaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPriceCocaKeyTyped
        JTextFieldUtils.onlyDigitsAndDecimalPointOnKeyTyped(evt);
    }//GEN-LAST:event_jTextFieldPriceCocaKeyTyped

    private void jTextFieldPrice7upKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPrice7upKeyTyped
        JTextFieldUtils.onlyDigitsAndDecimalPointOnKeyTyped(evt);
    }//GEN-LAST:event_jTextFieldPrice7upKeyTyped

    private void jTextFieldPriceFantaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPriceFantaKeyTyped
        JTextFieldUtils.onlyDigitsAndDecimalPointOnKeyTyped(evt);
    }//GEN-LAST:event_jTextFieldPriceFantaKeyTyped

    private void jTextFieldPriceSchwepsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPriceSchwepsKeyTyped
        JTextFieldUtils.onlyDigitsAndDecimalPointOnKeyTyped(evt);
    }//GEN-LAST:event_jTextFieldPriceSchwepsKeyTyped

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        jTextFieldPriceCoca.setText(""+VendingMachine.productCoca.getPrice());
        jTextFieldPrice7up.setText(""+VendingMachine.product7up.getPrice());
        jTextFieldPriceFanta.setText(""+VendingMachine.productFanta.getPrice());
        jTextFieldPriceSchweps.setText(""+VendingMachine.productSchweps.getPrice());
    }//GEN-LAST:event_formWindowOpened

    private void jTextField7upKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField7upKeyTyped
        JTextFieldUtils.onlyDigitsOnKeyTyped(evt);
    }//GEN-LAST:event_jTextField7upKeyTyped

    private void jTextFieldFantaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldFantaKeyTyped
        JTextFieldUtils.onlyDigitsOnKeyTyped(evt);
    }//GEN-LAST:event_jTextFieldFantaKeyTyped

    private void jTextFieldSchwepsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSchwepsKeyTyped
        JTextFieldUtils.onlyDigitsOnKeyTyped(evt);
    }//GEN-LAST:event_jTextFieldSchwepsKeyTyped

    private void jTextField7upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7upActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7upActionPerformed

    private void jButtonAddCokeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddCokeActionPerformed
        jTextFieldAddCoca.setText(""+ (Integer.parseInt(jTextFieldAddCoca.getText()) + 1));
    }//GEN-LAST:event_jButtonAddCokeActionPerformed

    private void jButtonSubstractCokeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubstractCokeActionPerformed
        if (Integer.parseInt(jTextFieldAddCoca.getText()) > 0)
            jTextFieldAddCoca.setText(""+ (Integer.parseInt(jTextFieldAddCoca.getText()) - 1));
    }//GEN-LAST:event_jButtonSubstractCokeActionPerformed

    private void jButtonAdd7UpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdd7UpActionPerformed
        jTextField7up.setText(""+ (Integer.parseInt(jTextField7up.getText()) + 1));
    }//GEN-LAST:event_jButtonAdd7UpActionPerformed

    private void jButtonAddFantaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddFantaActionPerformed
        jTextFieldFanta.setText(""+ (Integer.parseInt(jTextFieldFanta.getText()) + 1));
    }//GEN-LAST:event_jButtonAddFantaActionPerformed

    private void jButtonAddSchwepsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddSchwepsActionPerformed
        jTextFieldSchweps.setText(""+ (Integer.parseInt(jTextFieldSchweps.getText()) + 1));
    }//GEN-LAST:event_jButtonAddSchwepsActionPerformed

    private void jButtonSubstract7UpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubstract7UpActionPerformed
        if (Integer.parseInt(jTextField7up.getText()) > 0)
            jTextField7up.setText(""+ (Integer.parseInt(jTextField7up.getText()) - 1));
    }//GEN-LAST:event_jButtonSubstract7UpActionPerformed

    private void jButtonSubstractFantaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubstractFantaActionPerformed
        if (Integer.parseInt(jTextFieldFanta.getText()) > 0)
            jTextFieldFanta.setText(""+ (Integer.parseInt(jTextFieldFanta.getText()) - 1));
    }//GEN-LAST:event_jButtonSubstractFantaActionPerformed

    private void jButtonSubstractSchwepsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubstractSchwepsActionPerformed
        if (Integer.parseInt(jTextFieldSchweps.getText()) > 0)
            jTextFieldSchweps.setText(""+ (Integer.parseInt(jTextFieldSchweps.getText()) - 1));
    }//GEN-LAST:event_jButtonSubstractSchwepsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminAddProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminAddProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminAddProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminAddProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminAddProducts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd7Up;
    private javax.swing.JButton jButtonAddCoke;
    private javax.swing.JButton jButtonAddFanta;
    private javax.swing.JButton jButtonAddSchweps;
    private javax.swing.JButton jButtonAddStock;
    private javax.swing.JButton jButtonSubstract7Up;
    private javax.swing.JButton jButtonSubstractCoke;
    private javax.swing.JButton jButtonSubstractFanta;
    private javax.swing.JButton jButtonSubstractSchweps;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField7up;
    private javax.swing.JTextField jTextFieldAddCoca;
    private javax.swing.JTextField jTextFieldFanta;
    private javax.swing.JTextField jTextFieldPrice7up;
    private javax.swing.JTextField jTextFieldPriceCoca;
    private javax.swing.JTextField jTextFieldPriceFanta;
    private javax.swing.JTextField jTextFieldPriceSchweps;
    private javax.swing.JTextField jTextFieldSchweps;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    // End of variables declaration//GEN-END:variables
}
