/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.gti.asd.gui.vending;

import edu.gti.asd.gui.vending.model.MachineCoin;
import edu.gti.asd.gui.vending.model.MachineCoinsStock;
import edu.gti.asd.gui.vending.model.MachineCredit;
import edu.gti.asd.gui.vending.model.MachineOutput;
import edu.gti.asd.gui.vending.model.MachineProduct;
import edu.gti.asd.gui.vending.model.MachineSelectedProduct;
import edu.gti.asd.gui.vending.utils.ChangeUtil;
import edu.gti.asd.gui.vending.utils.Logger;
import java.math.BigDecimal;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author ariel
 */
public class VendingMachine extends javax.swing.JFrame {

    public static MachineCoinsStock coinStock;

    public static MachineProduct productCoca;
    public static MachineProduct product7up;
    public static MachineProduct productFanta;
    public static MachineProduct productSchweps;
        
    public static MachineCredit credit;
    public static MachineSelectedProduct selectedProduct;
    
    public static MachineOutput machineOutput;
    

    /**
     * Creates new form VendingMachine
     */
    public VendingMachine() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupProducts = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2e = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1e = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel50c = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel20c = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10c = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabelTotalMoney = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabelSelected = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabelPrice = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelCredit = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jToggleButtonCoca = new javax.swing.JToggleButton();
        jLabelCoca = new javax.swing.JLabel();
        jToggleButton7Up = new javax.swing.JToggleButton();
        jLabel7up = new javax.swing.JLabel();
        jToggleButtonFanta = new javax.swing.JToggleButton();
        jLabelFanta = new javax.swing.JLabel();
        jToggleButtonSchweps = new javax.swing.JToggleButton();
        jLabelSchweps = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jButtonPay = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabelOutputCoca = new javax.swing.JLabel();
        jLabelOutput7up = new javax.swing.JLabel();
        jLabelOutputFanta = new javax.swing.JLabel();
        jLabelOutputSchweps = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldOutput2e = new javax.swing.JTextField();
        jTextFieldOutput1e = new javax.swing.JTextField();
        jTextFieldOutput50c = new javax.swing.JTextField();
        jTextFieldOutput20c = new javax.swing.JTextField();
        jTextFieldOutput10c = new javax.swing.JTextField();
        jLabelOutputMessage = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        Admin = new javax.swing.JMenu();
        jMenuItemAddCoins = new javax.swing.JMenuItem();
        jMenuItemAddStock = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemClearAll = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jCheckBoxMenuItemShowProductStock = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItemShowCoinsStock = new javax.swing.JCheckBoxMenuItem();
        jMenuItemExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vending Machine");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Coins in stock"));

        jLabel6.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        jLabel6.setText("2e");
        jLabel6.setToolTipText("");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2e.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2e.setText("0");

        jLabel5.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        jLabel5.setText("1e");
        jLabel5.setToolTipText("");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel1e.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1e.setText("0");

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        jLabel3.setText("50c");
        jLabel3.setToolTipText("");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel50c.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel50c.setText("0");

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        jLabel4.setText("20c");
        jLabel4.setToolTipText("");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel20c.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20c.setText("0");

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        jLabel2.setText("10c");
        jLabel2.setToolTipText("");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel10c.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10c.setText("0");

        jLabel8.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Total $");
        jLabel8.setToolTipText("");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabelTotalMoney.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTotalMoney.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10c, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20c, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel50c, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1e, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2e, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                    .addComponent(jLabelTotalMoney, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6)
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10c)
                    .addComponent(jLabel20c)
                    .addComponent(jLabel50c)
                    .addComponent(jLabel1e)
                    .addComponent(jLabel2e)
                    .addComponent(jLabelTotalMoney))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Selected Product"));

        jLabel7.setText("Selected:");

        jLabelSelected.setBackground(new java.awt.Color(0, 0, 0));
        jLabelSelected.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        jLabelSelected.setForeground(new java.awt.Color(255, 0, 0));
        jLabelSelected.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSelected.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel9.setText("Price:");

        jLabelPrice.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        jLabelPrice.setForeground(new java.awt.Color(255, 0, 0));
        jLabelPrice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPrice.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelSelected, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabelSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Customer Credit"));

        jLabel1.setText("Credit:");

        jLabelCredit.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        jLabelCredit.setForeground(new java.awt.Color(255, 0, 0));
        jLabelCredit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCredit.setText("0");
        jLabelCredit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton1.setText("Open Wallet");
        jButton1.setToolTipText("Open Wallet to add money");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabelCredit, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(27, 27, 27))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelCredit)
                    .addComponent(jButton1))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Products"));

        buttonGroupProducts.add(jToggleButtonCoca);
        jToggleButtonCoca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/gti/asd/gui/vending/images/coca64.png"))); // NOI18N
        jToggleButtonCoca.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButtonCoca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonCocaActionPerformed(evt);
            }
        });

        jLabelCoca.setText("0");

        buttonGroupProducts.add(jToggleButton7Up);
        jToggleButton7Up.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/gti/asd/gui/vending/images/sevenup64.png"))); // NOI18N
        jToggleButton7Up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton7UpActionPerformed(evt);
            }
        });

        jLabel7up.setText("0");

        buttonGroupProducts.add(jToggleButtonFanta);
        jToggleButtonFanta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/gti/asd/gui/vending/images/fanta64.png"))); // NOI18N
        jToggleButtonFanta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonFantaActionPerformed(evt);
            }
        });

        jLabelFanta.setText("0");

        buttonGroupProducts.add(jToggleButtonSchweps);
        jToggleButtonSchweps.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/gti/asd/gui/vending/images/schweps64.png"))); // NOI18N
        jToggleButtonSchweps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonSchwepsActionPerformed(evt);
            }
        });

        jLabelSchweps.setText("0");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCoca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7up, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabelSchweps, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 6, Short.MAX_VALUE))
                    .addComponent(jLabelFanta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToggleButtonSchweps, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                    .addComponent(jToggleButtonFanta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToggleButton7Up, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToggleButtonCoca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jToggleButtonCoca, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabelCoca)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jToggleButton7Up, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel7up)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jToggleButtonFanta, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabelFanta)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabelSchweps))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jToggleButtonSchweps, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Actions"));

        jButtonPay.setText("Pay");
        jButtonPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPayActionPerformed(evt);
            }
        });

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonPay, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                    .addComponent(jButtonCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jButtonPay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButtonCancel)
                .addGap(26, 26, 26))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Output"));

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Get your can", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Liberation Sans", 0, 13), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel6.setLayout(new javax.swing.OverlayLayout(jPanel6));

        jLabelOutputCoca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/gti/asd/gui/vending/images/coca64.png"))); // NOI18N
        jLabelOutputCoca.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel6.add(jLabelOutputCoca);

        jLabelOutput7up.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/gti/asd/gui/vending/images/sevenup64.png"))); // NOI18N
        jPanel6.add(jLabelOutput7up);

        jLabelOutputFanta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/gti/asd/gui/vending/images/fanta64.png"))); // NOI18N
        jPanel6.add(jLabelOutputFanta);

        jLabelOutputSchweps.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/gti/asd/gui/vending/images/schweps64.png"))); // NOI18N
        jPanel6.add(jLabelOutputSchweps);

        jPanel8.setBackground(new java.awt.Color(0, 0, 0));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Get your Change", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Liberation Sans", 0, 13), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("2 euro");

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("1 euro");

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("50 cent");

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("20  cent");

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("10 cent");

        jTextFieldOutput2e.setEditable(false);
        jTextFieldOutput2e.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        jTextFieldOutput2e.setForeground(new java.awt.Color(255, 0, 0));
        jTextFieldOutput2e.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextFieldOutput1e.setEditable(false);
        jTextFieldOutput1e.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        jTextFieldOutput1e.setForeground(new java.awt.Color(255, 0, 0));
        jTextFieldOutput1e.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextFieldOutput50c.setEditable(false);
        jTextFieldOutput50c.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        jTextFieldOutput50c.setForeground(new java.awt.Color(255, 0, 0));
        jTextFieldOutput50c.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextFieldOutput20c.setEditable(false);
        jTextFieldOutput20c.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        jTextFieldOutput20c.setForeground(new java.awt.Color(255, 0, 0));
        jTextFieldOutput20c.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextFieldOutput10c.setEditable(false);
        jTextFieldOutput10c.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        jTextFieldOutput10c.setForeground(new java.awt.Color(255, 0, 0));
        jTextFieldOutput10c.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldOutput10c, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldOutput20c, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldOutput50c, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldOutput1e, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldOutput2e, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldOutput2e, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextFieldOutput1e, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextFieldOutput50c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextFieldOutput20c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTextFieldOutput10c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jLabelOutputMessage.setForeground(new java.awt.Color(255, 0, 0));
        jLabelOutputMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelOutputMessage.setText(" --- NOTHING TO GET ---");
        jLabelOutputMessage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton2.setText("Grab stuff");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelOutputMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabelOutputMessage)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        jPanel6.getAccessibleContext().setAccessibleName("Output");

        Admin.setMnemonic('A');
        Admin.setText("Admin");

        jMenuItemAddCoins.setMnemonic('C');
        jMenuItemAddCoins.setText("Add Coins");
        jMenuItemAddCoins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAddCoinsActionPerformed(evt);
            }
        });
        Admin.add(jMenuItemAddCoins);

        jMenuItemAddStock.setMnemonic('P');
        jMenuItemAddStock.setText("Add Products");
        jMenuItemAddStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAddStockActionPerformed(evt);
            }
        });
        Admin.add(jMenuItemAddStock);
        Admin.add(jSeparator1);

        jMenuItemClearAll.setMnemonic('a');
        jMenuItemClearAll.setText("Clear all");
        jMenuItemClearAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemClearAllActionPerformed(evt);
            }
        });
        Admin.add(jMenuItemClearAll);
        Admin.add(jSeparator2);

        jCheckBoxMenuItemShowProductStock.setSelected(true);
        jCheckBoxMenuItemShowProductStock.setText("Show product stock");
        jCheckBoxMenuItemShowProductStock.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBoxMenuItemShowProductStockStateChanged(evt);
            }
        });
        jCheckBoxMenuItemShowProductStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItemShowProductStockActionPerformed(evt);
            }
        });
        Admin.add(jCheckBoxMenuItemShowProductStock);

        jCheckBoxMenuItemShowCoinsStock.setSelected(true);
        jCheckBoxMenuItemShowCoinsStock.setText("Show coins stock");
        jCheckBoxMenuItemShowCoinsStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItemShowCoinsStockActionPerformed(evt);
            }
        });
        Admin.add(jCheckBoxMenuItemShowCoinsStock);

        jMenuItemExit.setMnemonic('x');
        jMenuItemExit.setText("Exit");
        jMenuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExitActionPerformed(evt);
            }
        });
        Admin.add(jMenuItemExit);

        jMenuBar1.add(Admin);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(36, 36, 36))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(108, 108, 108)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearAllStock() {
        clearCoinsStock();
        clearProductsStock();
        
    } 
    
    private void clearCoinsStock() {
        coinStock.reset();
    }
    
    private void clearProductsStock() {
        productCoca.resetStock();
        product7up.resetStock();
        productFanta.resetStock();
        productSchweps.resetStock();
    }
    
    private BigDecimal calculateTotalMoneyInStock() {        
        return coinStock.calculateTotalMoneyInStock();
    }
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Wallet wallet = new Wallet();
        wallet.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItemAddCoinsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAddCoinsActionPerformed
        AdminAddCoins addCoins = new AdminAddCoins();
        addCoins.setVisible(true);
    }//GEN-LAST:event_jMenuItemAddCoinsActionPerformed

    private void jButtonPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPayActionPerformed
        Logger.info("VendingMachine.jButtonPayActionPerformed", "Starting payment");
        if (selectedProduct != null && selectedProduct.getSelectedProduct() == null) {
            JOptionPane.showMessageDialog(this, "You must select a product first");
            return;
        }
        
        // Check stock
        if (selectedProduct.getSelectedProduct().getQuantity() <= 0) {
            JOptionPane.showMessageDialog(this, "There is no stock of " + selectedProduct.getSelectedProduct().getProductName() + " at the moment");
            return;
        }
        
        // Check money
        if (credit.getCredit().equals(BigDecimal.ZERO)) {
            JOptionPane.showMessageDialog(this, "Please enter the required amount: " + selectedProduct.getSelectedProduct().getPrice());
            return;
        }
        
        //if (credit.getCredit() < selectedProduct.getSelectedProduct().getPrice()) {
        if (credit.getCredit().compareTo(BigDecimal.valueOf(selectedProduct.getSelectedProduct().getPrice())) < 0 ) {
            JOptionPane.showMessageDialog(this, "More money is required. You added: " + credit.getCredit() + ", required:  " + selectedProduct.getSelectedProduct().getPrice());
            return;
        }
        
        // Check change
        BigDecimal difference = credit.getCredit().subtract(BigDecimal.valueOf(selectedProduct.getSelectedProduct().getPrice()));
        
        if (difference.equals(BigDecimal.ZERO) || difference.equals(new BigDecimal("0.0"))) {
            selectedProduct.getSelectedProduct().decrementStock(1);
            //JOptionPane.showMessageDialog(this, "Enjoy your " + selectedProduct.getSelectedProduct().getProductName() + "!!!");
            machineOutput.showOutput(selectedProduct.getSelectedProduct().getProductName(), null, "Enjoy your " + selectedProduct.getSelectedProduct().getProductName() + "!!!");
            ChangeUtil.updateStock(null, coinStock, credit);
        } else {
            // Give change
            List<Double> coinsToGive = ChangeUtil.calculateCoinsToGive(difference.doubleValue());
            if (ChangeUtil.checkCoinsStock(coinsToGive, coinStock)) {
                ChangeUtil.updateStock(coinsToGive, coinStock, credit);
                coinStock.calculateTotalMoneyInStock();
                selectedProduct.getSelectedProduct().decrementStock(1);
                //JOptionPane.showMessageDialog(this, "Get your change ["+ coinsToGive +"] and enjoy your " + selectedProduct.getSelectedProduct().getProductName() + "!!!");
                machineOutput.showOutput(selectedProduct.getSelectedProduct().getProductName(), coinsToGive, "Get your change and enjoy your " + selectedProduct.getSelectedProduct().getProductName() + "!!!");
                
            } else {
                JOptionPane.showMessageDialog(this, "Don't have the coins to give your change. Cancelling purchase...");
                credit.reset();
                selectedProduct.reset();
            }
            
            
        }
        
        // Resert credit and selected product
        credit.reset();
        selectedProduct.reset();
    }//GEN-LAST:event_jButtonPayActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Logger.info("VendingMachine.formWindowOpened", "Initializing components...");
        MachineCoin coin10c = new MachineCoin("10c", BigDecimal.valueOf(0.1), 0, jLabel10c);
        MachineCoin coin20c = new MachineCoin("20c", BigDecimal.valueOf(0.2), 0, jLabel20c);
        MachineCoin coin50c = new MachineCoin("50c", BigDecimal.valueOf(0.5), 0, jLabel50c);
        MachineCoin coin1e = new MachineCoin("1e", BigDecimal.valueOf(1), 0, jLabel1e);
        MachineCoin coin2e = new MachineCoin("2e", BigDecimal.valueOf(2), 0, jLabel2e);
        
        coinStock = new MachineCoinsStock(coin10c, coin20c, coin50c, coin1e, coin2e, jLabelTotalMoney);
        
        productCoca = new MachineProduct("Coke", 2.8, 0, jLabelCoca);
        product7up = new MachineProduct("7up", 2.7, 0, jLabel7up);
        productFanta = new MachineProduct("Fanta", 1.8, 0, jLabelFanta);
        productSchweps = new MachineProduct("Schweps",3.2, 0, jLabelSchweps);
        
        selectedProduct = new MachineSelectedProduct(jLabelSelected, jLabelPrice);
        
        credit = new MachineCredit(jLabelCredit);
        
        machineOutput = new MachineOutput(jLabelOutputMessage, jLabelOutputCoca, jLabelOutput7up, jLabelOutputFanta, jLabelOutputSchweps, jTextFieldOutput2e, jTextFieldOutput1e, jTextFieldOutput50c, jTextFieldOutput20c, jTextFieldOutput10c);
        
        jLabelOutputCoca.setVisible(false);
        jLabelOutput7up.setVisible(false);
        jLabelOutputFanta.setVisible(false);
        jLabelOutputSchweps.setVisible(false);
        
    }//GEN-LAST:event_formWindowOpened

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

    }//GEN-LAST:event_formWindowActivated

    private void jMenuItemAddStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAddStockActionPerformed
        AdminAddProducts products = new AdminAddProducts();
        products.setVisible(true);
    }//GEN-LAST:event_jMenuItemAddStockActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        
        if (selectedProduct.getSelectedProduct() == null) {
            JOptionPane.showMessageDialog(this, "Nothing to cancel");
            return;
        }
        
        int choice = JOptionPane.showConfirmDialog(this, "Are you sure you whant to cancell the purchase?");
        if (choice == 0) {
            if ( credit.getCredit() == null || credit.getCredit().equals(BigDecimal.ZERO) ) {
                JOptionPane.showMessageDialog(this, "No problem! Come back soon!");
            } else {
                JOptionPane.showMessageDialog(this, "No problem! Get your change [" + credit.getCredit() + "] and comeback anytime.");
            }
            
            credit.reset();
            selectedProduct.reset();
        }
        
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jToggleButtonCocaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonCocaActionPerformed
        // If customer hasn't taken its products and change yet, advice
        if (machineOutput.isEmpty()) {
            selectedProduct.setSelectedProduct(productCoca);
            selectedProduct.setToggleButton(jToggleButtonCoca);
        } else {
            JOptionPane.showMessageDialog(this, "The output area already has a can, please empty before proceed");
        }
    }//GEN-LAST:event_jToggleButtonCocaActionPerformed

    private void jToggleButton7UpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton7UpActionPerformed
        // If customer hasn't taken its products and change yet, advice
        if (machineOutput.isEmpty()) {
            selectedProduct.setSelectedProduct(product7up);
            selectedProduct.setToggleButton(jToggleButton7Up);
        } else {
            JOptionPane.showMessageDialog(this, "The output area already has a can, please empty before proceed");
        }
            
    }//GEN-LAST:event_jToggleButton7UpActionPerformed

    private void jToggleButtonFantaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonFantaActionPerformed
        // If customer hasn't taken its products and change yet, advice
        if (machineOutput.isEmpty()) {
            selectedProduct.setSelectedProduct(productFanta);
            selectedProduct.setToggleButton(jToggleButtonFanta);
        } else {
            JOptionPane.showMessageDialog(this, "The output area already has a can, please empty before proceed");
        }
    }//GEN-LAST:event_jToggleButtonFantaActionPerformed

    private void jToggleButtonSchwepsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonSchwepsActionPerformed
        // If customer hasn't taken its products and change yet, advice
        if (machineOutput.isEmpty()) {
            selectedProduct.setSelectedProduct(productSchweps);
            selectedProduct.setToggleButton(jToggleButtonSchweps);
        } else {
            JOptionPane.showMessageDialog(this, "The output area already has a can, please empty before proceed");
        }
    }//GEN-LAST:event_jToggleButtonSchwepsActionPerformed

    private void jMenuItemClearAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemClearAllActionPerformed
        int confirmation = JOptionPane.showConfirmDialog(this, "Are you sure you want to clear all stock (coins and products) from machine?");
        if (confirmation == 0) {
            clearAllStock();
        }
    }//GEN-LAST:event_jMenuItemClearAllActionPerformed

    private void jCheckBoxMenuItemShowProductStockStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItemShowProductStockStateChanged
    
    }//GEN-LAST:event_jCheckBoxMenuItemShowProductStockStateChanged

    private void jCheckBoxMenuItemShowProductStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItemShowProductStockActionPerformed
        if (jCheckBoxMenuItemShowProductStock.isSelected()) {
            showProductsStock();
        } else {
            hideProductsStock();
        }
        
    }//GEN-LAST:event_jCheckBoxMenuItemShowProductStockActionPerformed

    private void jCheckBoxMenuItemShowCoinsStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItemShowCoinsStockActionPerformed
        if (jCheckBoxMenuItemShowCoinsStock.isSelected()) {
            showCoinsStock();
        } else {
            hideCoinsStock();
        }
        
    }//GEN-LAST:event_jCheckBoxMenuItemShowCoinsStockActionPerformed

    private void jMenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExitActionPerformed
        dispose();
    }//GEN-LAST:event_jMenuItemExitActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        machineOutput.resetOutput();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VendingMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VendingMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VendingMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VendingMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VendingMachine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Admin;
    private javax.swing.ButtonGroup buttonGroupProducts;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonPay;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemShowCoinsStock;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemShowProductStock;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel10c;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel1e;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20c;
    private javax.swing.JLabel jLabel2e;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50c;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel7up;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCoca;
    private javax.swing.JLabel jLabelCredit;
    private javax.swing.JLabel jLabelFanta;
    private javax.swing.JLabel jLabelOutput7up;
    private javax.swing.JLabel jLabelOutputCoca;
    private javax.swing.JLabel jLabelOutputFanta;
    private javax.swing.JLabel jLabelOutputMessage;
    private javax.swing.JLabel jLabelOutputSchweps;
    private javax.swing.JLabel jLabelPrice;
    private javax.swing.JLabel jLabelSchweps;
    private javax.swing.JLabel jLabelSelected;
    private javax.swing.JLabel jLabelTotalMoney;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemAddCoins;
    private javax.swing.JMenuItem jMenuItemAddStock;
    private javax.swing.JMenuItem jMenuItemClearAll;
    private javax.swing.JMenuItem jMenuItemExit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JTextField jTextFieldOutput10c;
    private javax.swing.JTextField jTextFieldOutput1e;
    private javax.swing.JTextField jTextFieldOutput20c;
    private javax.swing.JTextField jTextFieldOutput2e;
    private javax.swing.JTextField jTextFieldOutput50c;
    private javax.swing.JToggleButton jToggleButton7Up;
    private javax.swing.JToggleButton jToggleButtonCoca;
    private javax.swing.JToggleButton jToggleButtonFanta;
    private javax.swing.JToggleButton jToggleButtonSchweps;
    // End of variables declaration//GEN-END:variables

    private void hideProductsStock() {
        productCoca.hideStock();
        product7up.hideStock();
        productFanta.hideStock();
        productSchweps.hideStock();

    }

    private void hideCoinsStock() {
        coinStock.getCoin10c().hideStock();
        coinStock.getCoin20c().hideStock();
        coinStock.getCoin50c().hideStock();
        coinStock.getCoin1e().hideStock();
        coinStock.getCoin2e().hideStock();
    }

    private void showProductsStock() {
        productCoca.showStock();
        product7up.showStock();
        productFanta.showStock();
        productSchweps.showStock();
    }

    private void showCoinsStock() {
        coinStock.getCoin10c().showStock();
        coinStock.getCoin20c().showStock();
        coinStock.getCoin50c().showStock();
        coinStock.getCoin1e().showStock();
        coinStock.getCoin2e().showStock();
    }
}
