/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.gti.asd.gui.vending;

import edu.gti.asd.gui.vending.utils.Logger;

/**
 *
 * @author ariel
 */
public class Wallet extends javax.swing.JFrame {
    
    public static int q10c;
    public static int q20c;
    public static int q50c;
    public static int q1e;
    public static int q2e;
    public static double moneyToAdd; 

    /**
     * Creates new form Wallet
     */
    public Wallet() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton10c = new javax.swing.JButton();
        jButton20c = new javax.swing.JButton();
        jButton50c = new javax.swing.JButton();
        jButton1e = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldTotalToAdd = new javax.swing.JTextField();
        jButtonAddMoney = new javax.swing.JButton();
        jButton2e = new javax.swing.JButton();
        jLabel10c = new javax.swing.JLabel();
        jLabel20c = new javax.swing.JLabel();
        jLabel50c = new javax.swing.JLabel();
        jLabel1e = new javax.swing.JLabel();
        jLabel2e = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Wallet");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jButton10c.setText("10c");
        jButton10c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10cActionPerformed(evt);
            }
        });

        jButton20c.setText("20c");
        jButton20c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20cActionPerformed(evt);
            }
        });

        jButton50c.setText("50c");
        jButton50c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton50cActionPerformed(evt);
            }
        });

        jButton1e.setText("1e");
        jButton1e.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1eActionPerformed(evt);
            }
        });

        jLabel1.setText("Total money to add ito the machine:");

        jTextFieldTotalToAdd.setText("0");

        jButtonAddMoney.setText("Add");
        jButtonAddMoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddMoneyActionPerformed(evt);
            }
        });

        jButton2e.setText("2e");
        jButton2e.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2eActionPerformed(evt);
            }
        });

        jLabel10c.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel20c.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel50c.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel1e.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel2e.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jTextFieldTotalToAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jButtonAddMoney))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel10c, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton10c, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton20c, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20c, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jButton50c, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel50c, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1e, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1e, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2e, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2e, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton10c, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton20c, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton50c, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1e, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2e, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10c, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20c, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel50c, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1e, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2e, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldTotalToAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jButtonAddMoney)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateMoney() {
        moneyToAdd = (q10c*0.10)+(q20c*0.20)+(q50c*0.50)+(q1e*1d)+(q2e*2d);
        Logger.info("Wallet.updateMoney", "Money to add: " + moneyToAdd);
        jTextFieldTotalToAdd.setText(""+moneyToAdd);
    }
    
    private void jButton10cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10cActionPerformed
        q10c++;
        jLabel10c.setText(""+q10c);
        updateMoney();
    }//GEN-LAST:event_jButton10cActionPerformed

    private void jButton20cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20cActionPerformed
        q20c++;
        jLabel20c.setText(""+q20c);
        updateMoney();
    }//GEN-LAST:event_jButton20cActionPerformed

    private void jButton50cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton50cActionPerformed
        q50c++;
        jLabel50c.setText(""+q50c);
        updateMoney();
    }//GEN-LAST:event_jButton50cActionPerformed

    private void jButton1eActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1eActionPerformed
        q1e++;
        jLabel1e.setText(""+q1e);
        updateMoney();
    }//GEN-LAST:event_jButton1eActionPerformed

    private void jButton2eActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2eActionPerformed
        q2e++;
        jLabel2e.setText(""+q2e);
        updateMoney();
    }//GEN-LAST:event_jButton2eActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        q10c = 0;
        q20c = 0;
        q50c = 0;
        q1e = 0;
        q2e = 0;
        
        jLabel10c.setText(""+q10c);
        jLabel20c.setText(""+q20c);
        jLabel50c.setText(""+q50c);
        jLabel1e.setText(""+q1e);
        jLabel2e.setText(""+q2e);
    }//GEN-LAST:event_formWindowOpened

    private void jButtonAddMoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddMoneyActionPerformed

        VendingMachine.credit.addCoins10c(q10c);
        VendingMachine.credit.addCoins20c(q20c);
        VendingMachine.credit.addCoins50c(q50c);
        VendingMachine.credit.addCoins1e(q1e);
        VendingMachine.credit.addCoins2e(q2e);
        VendingMachine.credit.calculateCredit();
        Logger.info("Wallet.jButtonAddMoneyActionPerformed" , "moneyToAdd: " + moneyToAdd);
        dispose();
    }//GEN-LAST:event_jButtonAddMoneyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Wallet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Wallet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Wallet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Wallet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Wallet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10c;
    private javax.swing.JButton jButton1e;
    private javax.swing.JButton jButton20c;
    private javax.swing.JButton jButton2e;
    private javax.swing.JButton jButton50c;
    private javax.swing.JButton jButtonAddMoney;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10c;
    private javax.swing.JLabel jLabel1e;
    private javax.swing.JLabel jLabel20c;
    private javax.swing.JLabel jLabel2e;
    private javax.swing.JLabel jLabel50c;
    private javax.swing.JTextField jTextFieldTotalToAdd;
    // End of variables declaration//GEN-END:variables
}
